name: Build from source and deploy to master

on:
  push:
    branches:
      - source
    
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: yarn install
      - run: gridsome build
#      - uses: peaceiris/actions-gh-pages@v3
#        with:
#          personal_token: ${{ secrets.JEKYLL_PAT }}
#          publish_dir: ./dist
#          publish_branch: master
